version: '3.4'
services:
  postgres:
    image: kartoza/postgis:13-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=volunthub
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - TZ=UTC
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgis

volumes:
  postgis-data:

networks:
  postgis: