"""initial schema

Revision ID: 7de456f85a15
Revises: 
Create Date: 2026-01-05 22:03:18.895523

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de456f85a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('time_begin', sa.Time(), nullable=True),
                    sa.Column('zone', sa.String(), nullable=True),
                    sa.Column('created_at', sa.String(), nullable=True),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326,
                                                                      dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
                    sa.Column('require_volunters',
                              sa.Boolean(), nullable=True),
                    sa.Column('volunters_required',
                              sa.Integer(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('materials_required',
                              sa.String(), nullable=True),
                    sa.Column('skills_required', sa.String(), nullable=True),
                    sa.Column('extra_data', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('avatar_url', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('inscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_user', sa.Integer(), nullable=False),
                    sa.Column('id_event', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_event'], ['events.id'], ),
                    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_inscriptions_id'),
                    'inscriptions', ['id'], unique=False)
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('priority', sa.String(), nullable=True),
                    sa.Column('completed_by', sa.Integer(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tasks_event_id'), 'tasks',
                    ['event_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_event_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_inscriptions_id'), table_name='inscriptions')
    op.drop_table('inscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('idx_events_location', table_name='events',
                  postgresql_using='gist')
    op.drop_table('events')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
